version: "3.8"
services:
  postgres-db:
    container_name: fos-postgres
    image: "postgres" # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: players
    ports:
      - "5432:5432"
